const wordHints = {
  'elephant': 'Large animal with trunk and big ears',
  'kangaroo': 'Australian animal that hops with pouch',
  'penguin': 'Black and white bird that cannot fly',
  'dolphin': 'Smart sea animal that jumps in water',
  'octopus': 'Sea creature with 8 arms',
  'butterfly': 'Colorful insect with wings',
  'alligator': 'Large reptile with big teeth in water',
  'crocodile': 'Similar to alligator, lives in water',
  'flamingo': 'Pink bird with long legs',
  'giraffe': 'Tallest animal with long neck',
  'zebra': 'Horse with black and white stripes',
  'gorilla': 'Large strong ape',
  'panda': 'Black and white bear from China',
  'koala': 'Gray animal from Australia, eats leaves',
  'raccoon': 'Animal with mask-like face and striped tail',
  'peacock': 'Bird with beautiful colorful tail feathers',
  'parrot': 'Colorful bird that can talk',
  'eagle': 'Large bird of prey with sharp talons',
  'pelican': 'Water bird with large beak pouch',
  'ostrich': 'Tallest bird that cannot fly',
  'toucan': 'Tropical bird with large colorful beak',
  'umbrella': 'Used to protect from rain',
  'backpack': 'Bag worn on back for carrying things',
  'suitcase': 'Box for carrying clothes when traveling',
  'keyboard': 'Computer device with letters and numbers',
  'telescope': 'Device to see stars and planets',
  'microscope': 'Device to see tiny things',
  'binoculars': 'Two tubes to see far away',
  'guitar': 'Musical instrument with 6 strings',
  'piano': 'Musical instrument with black and white keys',
  'violin': 'Small string instrument played with bow',
  'trumpet': 'Brass instrument you blow into',
  'saxophone': 'Curved brass instrument',
  'drums': 'Musical instrument you hit with sticks',
  'volcano': 'Mountain that erupts with lava',
  'waterfall': 'Water falling from high place',
  'rainbow': 'Colorful arc in sky after rain',
  'lightning': 'Electric flash in storm',
  'tornado': 'Spinning wind funnel',
  'sandwich': 'Food between two bread slices',
  'hamburger': 'Meat patty in round bun',
  'pizza': 'Round flat bread with cheese and toppings',
  'hotdog': 'Sausage in long bun',
  'sushi': 'Japanese food with rice and fish',
  'spaghetti': 'Long thin pasta noodles',
  'pancake': 'Flat round breakfast cake',
  'strawberry': 'Red fruit with seeds on outside',
  'pineapple': 'Tropical fruit with spiky crown',
  'watermelon': 'Large green fruit, red inside',
  'coconut': 'Brown hairy fruit with white inside',
  'avocado': 'Green fruit with large seed',
  'bicycle': 'Two-wheeled vehicle you pedal',
  'motorcycle': 'Two-wheeled vehicle with engine',
  'helicopter': 'Flying vehicle with spinning blades on top',
  'submarine': 'Underwater vehicle',
  'rocket': 'Vehicle that goes to space',
  'spaceship': 'Vehicle for space travel',
  'ambulance': 'Emergency vehicle for sick people',
  'firetruck': 'Red vehicle that fights fires',
  'bulldozer': 'Large vehicle that pushes dirt',
  'tractor': 'Farm vehicle',
  'lighthouse': 'Tall tower with light for ships',
  'windmill': 'Building with spinning blades',
  'fountain': 'Water spraying up in decoration',
  'pyramid': 'Triangle-shaped ancient building',
  'sphinx': 'Egyptian statue with human head and lion body',
  'snowman': 'Figure made of snow balls',
  'scarecrow': 'Dummy in field to scare birds',
  'vampire': 'Monster that drinks blood',
  'zombie': 'Walking dead person',
  'ghost': 'Floating spirit',
  'witch': 'Person with magic and pointy hat',
  'wizard': 'Man with magic and long beard',
  'pirate': 'Sea robber with eye patch',
  'ninja': 'Japanese warrior in black',
  'fireworks': 'Colorful explosions in sky',
  'balloon': 'Inflated rubber decoration',
  'eclipse': 'Moon blocking sun',
  'comet': 'Space rock with glowing tail',
  'astronaut': 'Person in space suit',
  'alien': 'Creature from another planet',
  'diamond': 'Precious clear gem',
  'necklace': 'Jewelry worn around neck',
  'bracelet': 'Jewelry worn on wrist',
  'treasure': 'Valuable items like gold and jewels',
  'campfire': 'Fire for camping',
  'hammock': 'Hanging bed between trees',
  'flashlight': 'Handheld light',
  'lantern': 'Portable light with handle',
  'snowflake': 'Six-pointed ice crystal',
  'icicle': 'Hanging ice spike',
  'glacier': 'Large slow-moving ice mass',
  'iceberg': 'Floating ice mountain',
  'cactus': 'Desert plant with spikes',
  'mushroom': 'Fungus with cap and stem',
  'starfish': 'Star-shaped sea creature',
  'jellyfish': 'Transparent sea creature with tentacles',
  'seahorse': 'Small horse-shaped fish',
  'refrigerator': 'Appliance to keep food cold',
  'microwave': 'Appliance to heat food quickly',
  'vacuum': 'Machine to clean floors',
  'lawnmower': 'Machine to cut grass',
  'chandelier': 'Fancy hanging light fixture',
  'trampoline': 'Bouncing mat for jumping',
  'ferris wheel': 'Giant rotating wheel with seats',
  'roller coaster': 'Fast track ride with ups and downs',
  'water slide': 'Slide with water',
  'parachute': 'Fabric that slows falling',
  'windmill': 'Structure with spinning blades',
  'drawbridge': 'Bridge that lifts up',
  'catapult': 'Device that launches objects',
  'wheelchair': 'Chair with wheels for disabled',
  'hourglass': 'Glass timer with sand',
  'sundial': 'Clock using sun shadow',
  'typewriter': 'Old machine for typing',
  'jukebox': 'Music playing machine',
  'headphones': 'Speakers worn on ears',
  'microphone': 'Device to amplify voice',
  'paintbrush': 'Brush for painting',
  'canvas': 'Cloth for painting on',
  'sculpture': 'Three-dimensional art',
  'sewing machine': 'Machine to stitch fabric',
  'treadmill': 'Exercise machine for running',
  'dumbbell': 'Weight for exercise',
  'stopwatch': 'Timer for sports',
  'whistle': 'Device that makes sharp sound',
  'chessboard': 'Board with black and white squares',
  'dominoes': 'Tiles with dots for game',
  'dice': 'Cubes with dots for games',
  'aquarium': 'Glass tank for fish',
  'birdcage': 'Cage for pet birds',
  'doghouse': 'Small house for dog',
  'beehive': 'Home for bees',
  'spiderweb': 'Net made by spider',
  'cocoon': 'Silk case for caterpillar',
  'shooting star': 'Meteor streaking across sky',
  'asteroid': 'Space rock',
  'space station': 'Building floating in space',
  'anchor': 'Heavy object to hold ship',
  'propeller': 'Spinning blades for movement',
  'mast': 'Tall pole on ship',
  'sail': 'Fabric to catch wind on boat',
  'hot air balloon': 'Floating balloon with basket',
  'glider': 'Plane without engine',
  'cockpit': 'Pilot area in plane',
  'runway': 'Long road for planes',
  'excavator': 'Digging machine with arm',
  'crane': 'Tall machine for lifting',
  'carousel': 'Rotating platform with horses',
  'puppet': 'Doll controlled by strings',
  'magic wand': 'Stick used by magician',
  'crystal ball': 'Glass sphere to see future',
  'genie lamp': 'Magic lamp with genie inside',
  'dragon': 'Mythical fire-breathing creature',
  'unicorn': 'Horse with horn on head',
  'pegasus': 'Horse with wings',
  'centaur': 'Half human, half horse',
  'mermaid': 'Half human, half fish',
  'fairy': 'Small magical creature with wings',
  'robot': 'Mechanical person',
  'UFO': 'Flying saucer from space',
  'lighthouse': 'Tower with light for ships',
  'skyscraper': 'Very tall building',
  'playground': 'Area with equipment for kids',
  'sandbox': 'Box filled with sand',
  'jungle gym': 'Climbing structure',
  'fishing rod': 'Pole for catching fish',
  'skateboard': 'Board with wheels for riding',
  'scooter': 'Two-wheeled standing vehicle',
  'ice skates': 'Boots with blades for ice',
  'skis': 'Long boards for snow',
  'snowboard': 'Wide board for snow',
  'surfboard': 'Board for riding waves',
  'kayak': 'Small narrow boat',
  'canoe': 'Narrow boat with paddles',
  'sailboat': 'Boat with sails',
  'mailbox': 'Box for receiving mail',
  'fire hydrant': 'Water source for firefighters',
  'traffic light': 'Signal with red, yellow, green lights',
  'stop sign': 'Red octagon sign',
  'fountain': 'Decorative water feature',
  'camera': 'Device to take photos',
  'tripod': 'Three-legged stand for camera'
};

const words = {
  easy: [
    'cat', 'dog', 'fish', 'bird', 'cow', 'pig', 'duck', 'frog', 'bear', 'lion',
    'tiger', 'wolf', 'fox', 'deer', 'goat', 'sheep', 'horse', 'mouse', 'rat', 'bat',
    'bee', 'ant', 'fly', 'bug', 'crab', 'seal', 'whale', 'shark', 'snake', 'lizard',
    'turtle', 'snail', 'worm', 'spider', 'owl', 'hawk', 'crow', 'swan', 'dove', 'hen',
    'pen', 'cup', 'mug', 'bowl', 'plate', 'fork', 'knife', 'spoon', 'pot', 'pan',
    'jar', 'can', 'box', 'bag', 'bin', 'tub', 'bucket', 'basket', 'key', 'lock',
    'door', 'gate', 'fence', 'wall', 'roof', 'window', 'glass', 'mirror', 'lamp', 'candle',
    'tree', 'bush', 'flower', 'rose', 'grass', 'leaf', 'sun', 'moon', 'star', 'cloud',
    'rain', 'snow', 'wind', 'sky', 'water', 'fire', 'ice', 'rock', 'sand', 'hill',
    'head', 'face', 'eye', 'ear', 'nose', 'mouth', 'hand', 'foot', 'arm', 'leg',
    'hat', 'cap', 'shoe', 'sock', 'shirt', 'pants', 'coat', 'dress', 'ring', 'watch',
    'car', 'bus', 'bike', 'train', 'plane', 'boat', 'ship', 'truck', 'van', 'taxi',
    'book', 'pen', 'paper', 'desk', 'chair', 'table', 'bed', 'sofa', 'clock', 'phone',
    'apple', 'banana', 'orange', 'grape', 'lemon', 'bread', 'milk', 'egg', 'meat', 'cake',
    'ball', 'kite', 'doll', 'toy', 'drum', 'bell', 'flag', 'gift', 'card', 'coin',
    'smile', 'cry', 'laugh', 'sleep', 'run', 'walk', 'jump', 'dance', 'sing', 'clap',
    'heart', 'arrow', 'cross', 'circle', 'square', 'line', 'dot', 'wave', 'spiral', 'zigzag',
    'house', 'tent', 'cave', 'barn', 'shed', 'hut', 'igloo', 'castle', 'tower', 'bridge',
    'sword', 'shield', 'bow', 'axe', 'hammer', 'saw', 'nail', 'screw', 'rope', 'chain',
    'crown', 'ring', 'medal', 'trophy', 'prize', 'ticket', 'stamp', 'badge', 'button', 'zipper'
  ],

  medium: [
    'elephant', 'kangaroo', 'penguin', 'dolphin', 'octopus', 'butterfly', 'dragonfly', 'alligator', 'crocodile', 'flamingo',
    'giraffe', 'zebra', 'monkey', 'gorilla', 'panda', 'koala', 'raccoon', 'squirrel', 'beaver', 'otter',
    'peacock', 'parrot', 'eagle', 'vulture', 'pelican', 'ostrich', 'toucan', 'hummingbird', 'woodpecker', 'kingfisher',
    'umbrella', 'backpack', 'suitcase', 'briefcase', 'wallet', 'purse', 'handbag', 'luggage', 'toolbox', 'lunchbox',
    'keyboard', 'monitor', 'printer', 'camera', 'telescope', 'microscope', 'binoculars', 'compass', 'thermometer', 'calculator',
    'guitar', 'piano', 'violin', 'trumpet', 'saxophone', 'drums', 'flute', 'harp', 'banjo', 'accordion',
    'mountain', 'volcano', 'waterfall', 'rainbow', 'lightning', 'tornado', 'island', 'desert', 'forest', 'jungle',
    'sandwich', 'hamburger', 'pizza', 'hotdog', 'taco', 'burrito', 'sushi', 'noodles', 'spaghetti', 'pancake',
    'strawberry', 'pineapple', 'watermelon', 'coconut', 'avocado', 'broccoli', 'carrot', 'cucumber', 'tomato', 'potato',
    'bicycle', 'motorcycle', 'helicopter', 'submarine', 'rocket', 'spaceship', 'ambulance', 'firetruck', 'bulldozer', 'tractor',
    'lighthouse', 'windmill', 'fountain', 'statue', 'pyramid', 'sphinx', 'temple', 'pagoda', 'mosque', 'cathedral',
    'football', 'basketball', 'baseball', 'volleyball', 'tennis', 'hockey', 'golf', 'bowling', 'archery', 'boxing',
    'snowman', 'scarecrow', 'mummy', 'vampire', 'zombie', 'ghost', 'witch', 'wizard', 'pirate', 'ninja',
    'birthday', 'wedding', 'fireworks', 'balloon', 'confetti', 'candles', 'presents', 'ribbon', 'wreath', 'garland',
    'sunrise', 'sunset', 'eclipse', 'comet', 'meteor', 'galaxy', 'planet', 'satellite', 'astronaut', 'alien',
    'diamond', 'emerald', 'ruby', 'pearl', 'necklace', 'bracelet', 'earring', 'treasure', 'chest', 'map',
    'campfire', 'bonfire', 'barbecue', 'picnic', 'hammock', 'sleeping bag', 'flashlight', 'lantern', 'matches', 'firewood',
    'snowflake', 'icicle', 'avalanche', 'blizzard', 'glacier', 'iceberg', 'penguin', 'polar bear', 'walrus', 'seal',
    'cactus', 'palm tree', 'bamboo', 'mushroom', 'seaweed', 'coral', 'starfish', 'jellyfish', 'seahorse', 'clownfish',
    'magnet', 'battery', 'lightbulb', 'switch', 'plug', 'socket', 'wire', 'antenna', 'satellite dish', 'solar panel'
  ],

  hard: [
    'refrigerator', 'microwave', 'blender', 'toaster', 'vacuum', 'lawnmower', 'chainsaw', 'forklift', 'chandelier', 'bookshelf',
    'wardrobe', 'trampoline', 'seesaw', 'ferris wheel', 'roller coaster', 'water slide', 'diving board', 'parachute', 'scarecrow', 'windmill',
    'drawbridge', 'catapult', 'bandage', 'crutches', 'wheelchair', 'stretcher', 'telescope', 'microscope', 'hourglass', 'sundial',
    'typewriter', 'jukebox', 'speaker', 'headphones', 'microphone', 'paintbrush', 'canvas', 'sculpture', 'sewing machine', 'treadmill',
    'dumbbell', 'jump rope', 'stopwatch', 'whistle', 'scoreboard', 'trophy', 'chessboard', 'dominoes', 'dice', 'playing cards',
    'aquarium', 'birdcage', 'doghouse', 'beehive', 'anthill', 'spiderweb', 'cocoon', 'nest', 'shooting star', 'asteroid',
    'space station', 'submarine', 'anchor', 'propeller', 'mast', 'sail', 'oar', 'paddle', 'lifeboat', 'parachute',
    'hot air balloon', 'glider', 'cockpit', 'runway', 'excavator', 'crane', 'dump truck', 'garbage truck', 'tow truck', 'snowplow',
    'carousel', 'puppet', 'magic wand', 'crystal ball', 'fortune cookie', 'genie lamp', 'totem pole', 'dreamcatcher', 'boomerang', 'sombrero',
    'dragon', 'unicorn', 'pegasus', 'centaur', 'sphinx', 'mermaid', 'fairy', 'elf', 'goblin', 'troll',
    'robot', 'cyborg', 'android', 'spaceship', 'UFO', 'satellite', 'radar', 'antenna', 'solar panel', 'windmill',
    'lighthouse', 'skyscraper', 'factory', 'warehouse', 'barn', 'stable', 'garage', 'hangar', 'airport', 'seaport',
    'playground', 'sandbox', 'slide', 'swing', 'jungle gym', 'monkey bars', 'balance beam', 'hopscotch', 'tetherball', 'basketball hoop',
    'campsite', 'tent', 'sleeping bag', 'backpack', 'compass', 'map', 'binoculars', 'flashlight', 'lantern', 'campfire',
    'fishing rod', 'fishing net', 'tackle box', 'bait', 'hook', 'anchor', 'buoy', 'life jacket', 'snorkel', 'scuba tank',
    'skateboard', 'scooter', 'rollerblades', 'ice skates', 'skis', 'snowboard', 'sled', 'toboggan', 'surfboard', 'kayak',
    'canoe', 'raft', 'sailboat', 'motorboat', 'yacht', 'cruise ship', 'tugboat', 'barge', 'houseboat', 'pontoon',
    'tractor', 'combine', 'plow', 'harvester', 'sprinkler', 'scarecrow', 'silo', 'barn', 'fence', 'gate',
    'mailbox', 'fire hydrant', 'street lamp', 'traffic light', 'stop sign', 'parking meter', 'bench', 'fountain', 'statue', 'monument',
    'telescope', 'binoculars', 'camera', 'tripod', 'lens', 'flash', 'film', 'projector', 'screen', 'spotlight'
  ]
};

module.exports = { words, wordHints };
